theme: jekyll-theme-cayman
title: Tiny Actions Challenge
description:
- ActivityNet workshop, CVPR 2022
- June 2022
- New Orleans, Louisiana
buttons:
  Tasks: '#tasks'
  Dataset: '#dataset-details'
  Evaluation: '#evaluation'
  Important Dates: '#important-dates'
  Organizers: '#organizers'
  Cite: '#references'
  Contact: '#contact'
github:
  is_project_page: false
