theme: jekyll-theme-cayman
title: Tiny Actions Challenge
description:
- CVPR 2022 workshop
- June 2022
- New Orleans, Louisiana
buttons:
  About: '#about'
  Dataset: '#dataset'
  Evaluation: '#evaluation'
  Important Dates: '#important-dates'
  Organizers: '#organizers'
  Contact: '#contact'
github:
  is_project_page: false
